# Generated by Django 4.2.1 on 2023-07-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Member_Account', models.CharField(max_length=200)),
                ('Member_Password', models.CharField(max_length=200)),
                ('Member_Email', models.EmailField(blank=True, max_length=200)),
                ('Member_Name', models.CharField(max_length=200)),
                ('Member_PaySituation', models.BooleanField()),
            ],
        ),
    ]
