# Generated by Django 4.2.5 on 2023-09-24 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='store',
            fields=[
                ('storeid', models.AutoField(primary_key=True, serialize=False)),
                ('storename', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='dj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('msgtime', models.CharField(max_length=50)),
                ('star', models.PositiveIntegerField()),
                ('comment', models.CharField(max_length=5000)),
                ('effflag', models.PositiveIntegerField()),
                ('storeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gapp.store')),
            ],
        ),
    ]
