# Generated by Django 4.2.1 on 2023-07-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Manager_Account', models.CharField(max_length=200)),
                ('Manager_Password', models.CharField(max_length=200)),
                ('Manager_Name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserIP', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='Create Day')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Visitor_Account', models.CharField(max_length=200)),
                ('Visitor_Password', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='Create Day')),
            ],
        ),
    ]
