# Generated by Django 4.2.1 on 2023-07-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gapp', '0002_manager_user_visitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SearchHistory_SearchShop', models.CharField(max_length=200)),
                ('SearchHistory_SearchTime', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ShopInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShopInformation_URL', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='VIPInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VIPInformation_Collect', models.CharField(max_length=200)),
                ('VIPInformation_Feadback', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='Member',
            new_name='VIP',
        ),
        migrations.DeleteModel(
            name='Visitor',
        ),
        migrations.RenameField(
            model_name='vip',
            old_name='Member_Account',
            new_name='VIP_Account',
        ),
        migrations.RenameField(
            model_name='vip',
            old_name='Member_Email',
            new_name='VIP_Email',
        ),
        migrations.RenameField(
            model_name='vip',
            old_name='Member_Name',
            new_name='VIP_Name',
        ),
        migrations.RenameField(
            model_name='vip',
            old_name='Member_Password',
            new_name='VIP_Password',
        ),
        migrations.RenameField(
            model_name='vip',
            old_name='Member_PaySituation',
            new_name='VIP_PaySituation',
        ),
    ]
