# Generated by Django 4.2.1 on 2023-07-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gapp', '0004_mes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mes',
            old_name='ShopName',
            new_name='Mes_Percent',
        ),
        migrations.RenameField(
            model_name='shopinformation',
            old_name='ShopInformation_URL',
            new_name='ShopInformation_Name',
        ),
        migrations.AddField(
            model_name='mes',
            name='Mes_judge',
            field=models.BooleanField(default=False),
        ),
    ]
