# Generated by Django 4.2.1 on 2023-07-20 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gapp', '0007_alter_manager_manager_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mes',
            name='ShopName',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Gapp.shopinformation'),
        ),
    ]
