# Generated by Django 4.2.1 on 2023-08-20 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gapp', '0010_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='AdressName',
            field=models.CharField(default='', max_length=500),
        ),
    ]
