# Generated by Django 4.2.1 on 2023-08-20 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gapp', '0011_adress_adressname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adress',
            new_name='ADR',
        ),
    ]
