# Generated by Django 4.2.1 on 2023-08-20 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gapp', '0012_rename_adress_adr'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ADR',
            new_name='Adress',
        ),
    ]
