# Generated by Django 4.2.1 on 2023-08-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gapp', '0013_rename_adr_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='latitude',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='adress',
            name='longitude',
            field=models.CharField(default='', max_length=500),
        ),
    ]
