# Generated by Django 4.2.1 on 2023-08-20 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gapp', '0017_rename_adrss_adresss'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adresss',
            new_name='Adress',
        ),
    ]
