# Generated by Django 4.2.1 on 2023-08-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gapp', '0018_rename_adresss_adress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Adress',
        ),
        migrations.RemoveField(
            model_name='vipinformation',
            name='VIPInformation_Collect',
        ),
        migrations.RemoveField(
            model_name='vipinformation',
            name='VIPInformation_Feadback',
        ),
        migrations.AddField(
            model_name='vipinformation',
            name='AdressName',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='vipinformation',
            name='latitude',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='vipinformation',
            name='longitude',
            field=models.CharField(default='', max_length=500),
        ),
    ]
