# Generated by Django 4.2.1 on 2023-08-20 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gapp', '0020_search_remove_vipinformation_adressname_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Search',
            new_name='Adress',
        ),
    ]
