# Generated by Django 4.2.5 on 2023-09-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gapp', '0021_rename_search_adress'),
    ]

    operations = [
        migrations.CreateModel(
            name='ccc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('msgtime', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=5000)),
            ],
        ),
    ]
