# Generated by Django 4.2.5 on 2023-09-23 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gapp', '0022_ccc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ccc',
            new_name='dj',
        ),
    ]
