# Generated by Django 4.2.5 on 2023-09-23 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gapp', '0023_rename_ccc_dj'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Adress',
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
        migrations.DeleteModel(
            name='Mes',
        ),
        migrations.DeleteModel(
            name='SearchHistory',
        ),
        migrations.DeleteModel(
            name='ShopInformation',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='VIP',
        ),
        migrations.DeleteModel(
            name='VIPInformation',
        ),
    ]
