# Generated by Django 4.2.5 on 2023-11-12 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='storeid',
        ),
    ]
