# Generated by Django 4.2.5 on 2023-11-05 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gapp', '0002_effective_favoritelocation_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavoriteLocation',
        ),
    ]
