# Generated by Django 4.2.5 on 2023-11-05 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gapp', '0003_delete_favoritelocation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='effective',
        ),
    ]
