# Generated by Django 4.2.1 on 2023-07-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gapp', '0003_searchhistory_shopinformation_vipinformation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShopName', models.CharField(max_length=100)),
            ],
        ),
    ]
