# Generated by Django 4.2.1 on 2023-07-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gapp', '0005_rename_shopname_mes_mes_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mes',
            name='Mes_Stars',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='mes',
            name='Mes_Suspicious',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='SearchHistory_SearchShop',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='SearchHistory_SearchTime',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='shopinformation',
            name='ShopInformation_Name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='vipinformation',
            name='VIPInformation_Collect',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='vipinformation',
            name='VIPInformation_Feadback',
            field=models.CharField(default='', max_length=200),
        ),
    ]
