# Generated by Django 4.2.1 on 2023-07-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gapp', '0006_mes_mes_stars_mes_mes_suspicious_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='Manager_Account',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='manager',
            name='Manager_Name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='manager',
            name='Manager_Password',
            field=models.CharField(default='', max_length=200),
        ),
    ]
