# Generated by Django 4.2.1 on 2023-08-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gapp', '0009_remove_mes_mes_judge_remove_mes_shopname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.CharField(max_length=500)),
                ('latitude', models.CharField(max_length=500)),
            ],
        ),
    ]
