# Generated by Django 4.2.1 on 2023-08-20 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gapp', '0014_alter_adress_latitude_alter_adress_longitude'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adress',
            new_name='Adrs',
        ),
    ]
