# Generated by Django 4.2.1 on 2023-08-20 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gapp', '0015_rename_adress_adrs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adrs',
            new_name='Adrss',
        ),
    ]
