# Generated by Django 4.2.1 on 2023-08-20 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gapp', '0016_rename_adrs_adrss'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adrss',
            new_name='Adresss',
        ),
    ]
