# Generated by Django 4.2.5 on 2023-09-27 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dj',
            old_name='storeid',
            new_name='storeid_id',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='storeid',
            new_name='storeid_id',
        ),
    ]
